### ISSUE TITLE
Employee analisise

### ISSUE THREAD

**Issue by obert281** [Zeeshan1805/HR-Analytics-Dashboard-Power-Bi#1]
[UNIISCED - Quadro de Pessoal  2024.xls](https://github.com/user-attachments/files/16813691/UNIISCED.-.Quadro.de.Pessoal.2024.xls)
[UNIISCED - Quadro de Pessoal  2024.xls](https://github.com/user-attachments/files/16813696/UNIISCED.-.Quadro.de.Pessoal.2024.xls)

**Comment by Zeeshan1805** [comment]
Can you explain in English?On 30-Aug-2024, at 1:16 PM, obert281 ***@***.***> wrote:﻿
Closed #1 as completed.
